logo: http://www.itelazpi.eus/wp-content/uploads/DonBosco_logo.jpg
copyright: Aitor Iturrioz # will override the copyright notice (default is site title)
search: false # hides this page from search results

plugins:
  - jekyll-remote-theme
remote_theme: chromatical/jekyll-materialdocs
